package com.thinkgem.jeesite.modules.video_m_n.dao;

import com.thinkgem.jeesite.common.persistence.annotation.MyBatisDao;
import com.thinkgem.jeesite.modules.video_m_n.entity.MusicTableCount;

@MyBatisDao
public interface MusicTableCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    int insert(MusicTableCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    int insertSelective(MusicTableCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    MusicTableCount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    int updateByPrimaryKeySelective(MusicTableCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_table_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    int updateByPrimaryKey(MusicTableCount record);
}