package com.thinkgem.jeesite.modules.video_m_n.entity;

import java.io.Serializable;

public class MusicTableCount implements Serializable {
	
	private String musicDownAddress;
    public String getMusicDownAddress() {
		return musicDownAddress;
	}

	public void setMusicDownAddress(String musicDownAddress) {
		this.musicDownAddress = musicDownAddress;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.music_id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer musicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.music_address
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String musicAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.music_play_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer musicPlayCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.music_like_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer musicLikeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.music_hite_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer musicHiteCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.music_order
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer musicOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.ATTRA
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.ATTRB
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.ATTRC
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.ATTRD
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.ATTRE
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.ATTRF
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_table_count.ATTRG
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table music_table_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.id
     *
     * @return the value of music_table_count.id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.id
     *
     * @param id the value for music_table_count.id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.music_id
     *
     * @return the value of music_table_count.music_id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getMusicId() {
        return musicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.music_id
     *
     * @param musicId the value for music_table_count.music_id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setMusicId(Integer musicId) {
        this.musicId = musicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.music_address
     *
     * @return the value of music_table_count.music_address
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getMusicAddress() {
        return musicAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.music_address
     *
     * @param musicAddress the value for music_table_count.music_address
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setMusicAddress(String musicAddress) {
        this.musicAddress = musicAddress == null ? null : musicAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.music_play_count
     *
     * @return the value of music_table_count.music_play_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getMusicPlayCount() {
        return musicPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.music_play_count
     *
     * @param musicPlayCount the value for music_table_count.music_play_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setMusicPlayCount(Integer musicPlayCount) {
        this.musicPlayCount = musicPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.music_like_count
     *
     * @return the value of music_table_count.music_like_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getMusicLikeCount() {
        return musicLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.music_like_count
     *
     * @param musicLikeCount the value for music_table_count.music_like_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setMusicLikeCount(Integer musicLikeCount) {
        this.musicLikeCount = musicLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.music_hite_count
     *
     * @return the value of music_table_count.music_hite_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getMusicHiteCount() {
        return musicHiteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.music_hite_count
     *
     * @param musicHiteCount the value for music_table_count.music_hite_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setMusicHiteCount(Integer musicHiteCount) {
        this.musicHiteCount = musicHiteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.music_order
     *
     * @return the value of music_table_count.music_order
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getMusicOrder() {
        return musicOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.music_order
     *
     * @param musicOrder the value for music_table_count.music_order
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setMusicOrder(Integer musicOrder) {
        this.musicOrder = musicOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.ATTRA
     *
     * @return the value of music_table_count.ATTRA
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttra() {
        return attra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.ATTRA
     *
     * @param attra the value for music_table_count.ATTRA
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttra(String attra) {
        this.attra = attra == null ? null : attra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.ATTRB
     *
     * @return the value of music_table_count.ATTRB
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrb() {
        return attrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.ATTRB
     *
     * @param attrb the value for music_table_count.ATTRB
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrb(String attrb) {
        this.attrb = attrb == null ? null : attrb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.ATTRC
     *
     * @return the value of music_table_count.ATTRC
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrc() {
        return attrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.ATTRC
     *
     * @param attrc the value for music_table_count.ATTRC
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrc(String attrc) {
        this.attrc = attrc == null ? null : attrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.ATTRD
     *
     * @return the value of music_table_count.ATTRD
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrd() {
        return attrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.ATTRD
     *
     * @param attrd the value for music_table_count.ATTRD
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrd(String attrd) {
        this.attrd = attrd == null ? null : attrd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.ATTRE
     *
     * @return the value of music_table_count.ATTRE
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttre() {
        return attre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.ATTRE
     *
     * @param attre the value for music_table_count.ATTRE
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttre(String attre) {
        this.attre = attre == null ? null : attre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.ATTRF
     *
     * @return the value of music_table_count.ATTRF
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrf() {
        return attrf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.ATTRF
     *
     * @param attrf the value for music_table_count.ATTRF
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrf(String attrf) {
        this.attrf = attrf == null ? null : attrf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_table_count.ATTRG
     *
     * @return the value of music_table_count.ATTRG
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrg() {
        return attrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_table_count.ATTRG
     *
     * @param attrg the value for music_table_count.ATTRG
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrg(String attrg) {
        this.attrg = attrg == null ? null : attrg.trim();
    }
}