package com.thinkgem.jeesite.modules.video_m_n.entity;

import java.io.Serializable;

public class NovelTableCount implements Serializable {
	
	private String novelDownAddress;
    public String getNovelDownAddress() {
		return novelDownAddress;
	}

	public void setNovelDownAddress(String novelDownAddress) {
		this.novelDownAddress = novelDownAddress;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.novel_id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer novelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.novel_content
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String novelContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.novel_play_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer novelPlayCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.novel_like_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer novelLikeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.novel_hite_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer novelHiteCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.novel_order
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private Integer novelOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.ATTRA
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.ATTRB
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.ATTRC
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.ATTRD
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.ATTRE
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.ATTRF
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column novel_table_count.ATTRG
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private String attrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table novel_table_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.id
     *
     * @return the value of novel_table_count.id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.id
     *
     * @param id the value for novel_table_count.id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.novel_id
     *
     * @return the value of novel_table_count.novel_id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getNovelId() {
        return novelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.novel_id
     *
     * @param novelId the value for novel_table_count.novel_id
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setNovelId(Integer novelId) {
        this.novelId = novelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.novel_content
     *
     * @return the value of novel_table_count.novel_content
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getNovelContent() {
        return novelContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.novel_content
     *
     * @param novelContent the value for novel_table_count.novel_content
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setNovelContent(String novelContent) {
        this.novelContent = novelContent == null ? null : novelContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.novel_play_count
     *
     * @return the value of novel_table_count.novel_play_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getNovelPlayCount() {
        return novelPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.novel_play_count
     *
     * @param novelPlayCount the value for novel_table_count.novel_play_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setNovelPlayCount(Integer novelPlayCount) {
        this.novelPlayCount = novelPlayCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.novel_like_count
     *
     * @return the value of novel_table_count.novel_like_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getNovelLikeCount() {
        return novelLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.novel_like_count
     *
     * @param novelLikeCount the value for novel_table_count.novel_like_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setNovelLikeCount(Integer novelLikeCount) {
        this.novelLikeCount = novelLikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.novel_hite_count
     *
     * @return the value of novel_table_count.novel_hite_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getNovelHiteCount() {
        return novelHiteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.novel_hite_count
     *
     * @param novelHiteCount the value for novel_table_count.novel_hite_count
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setNovelHiteCount(Integer novelHiteCount) {
        this.novelHiteCount = novelHiteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.novel_order
     *
     * @return the value of novel_table_count.novel_order
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public Integer getNovelOrder() {
        return novelOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.novel_order
     *
     * @param novelOrder the value for novel_table_count.novel_order
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setNovelOrder(Integer novelOrder) {
        this.novelOrder = novelOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.ATTRA
     *
     * @return the value of novel_table_count.ATTRA
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttra() {
        return attra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.ATTRA
     *
     * @param attra the value for novel_table_count.ATTRA
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttra(String attra) {
        this.attra = attra == null ? null : attra.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.ATTRB
     *
     * @return the value of novel_table_count.ATTRB
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrb() {
        return attrb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.ATTRB
     *
     * @param attrb the value for novel_table_count.ATTRB
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrb(String attrb) {
        this.attrb = attrb == null ? null : attrb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.ATTRC
     *
     * @return the value of novel_table_count.ATTRC
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrc() {
        return attrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.ATTRC
     *
     * @param attrc the value for novel_table_count.ATTRC
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrc(String attrc) {
        this.attrc = attrc == null ? null : attrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.ATTRD
     *
     * @return the value of novel_table_count.ATTRD
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrd() {
        return attrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.ATTRD
     *
     * @param attrd the value for novel_table_count.ATTRD
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrd(String attrd) {
        this.attrd = attrd == null ? null : attrd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.ATTRE
     *
     * @return the value of novel_table_count.ATTRE
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttre() {
        return attre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.ATTRE
     *
     * @param attre the value for novel_table_count.ATTRE
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttre(String attre) {
        this.attre = attre == null ? null : attre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.ATTRF
     *
     * @return the value of novel_table_count.ATTRF
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrf() {
        return attrf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.ATTRF
     *
     * @param attrf the value for novel_table_count.ATTRF
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrf(String attrf) {
        this.attrf = attrf == null ? null : attrf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column novel_table_count.ATTRG
     *
     * @return the value of novel_table_count.ATTRG
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public String getAttrg() {
        return attrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column novel_table_count.ATTRG
     *
     * @param attrg the value for novel_table_count.ATTRG
     *
     * @mbggenerated Mon Nov 28 22:59:27 CST 2016
     */
    public void setAttrg(String attrg) {
        this.attrg = attrg == null ? null : attrg.trim();
    }
}